name: Clojure CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: clojure:openjdk-17-tools-deps

    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2

    - name: Test
      run: |
        clojure -X:check
        clojure -X:test

    - name: Lint & Format
      run: |
        clojure -T:project format-check
        clojure -T:project lint
